### ISSUE TITLE
modify the rule filter_offtarget_variants or fix_delly_calls

### ISSUE THREAD

**Issue by user-tq** [snakemake-workflows/dna-seq-varlociraptor#216]
get erro
```
[E::idx_find_and_load] Could not retrieve index file for 'results/candidate-calls/2022NC.delly.no_bnds.bcf'
Failed to read from results/candidate-calls/2022NC.delly.no_bnds.bcf: could not load index
```
![image](https://user-images.githubusercontent.com/72878144/224495914-b33e40f7-8c3f-4e71-9893-e4e7721add8a.png)
Maybe it can be changed to
```
rule fix_delly_calls:
    input:
        "results/candidate-calls/{group}.delly.bcf",
    output:
        "results/candidate-calls/{group}.delly.no_bnds.bcf",
    log:
        "logs/fix_delly_calls/{group}.log",
    conda:
        "../envs/bcftools.yaml"
    shell:
        """bcftools view -e 'INFO/SVTYPE="BND"' {input} -Ob > {output} 2> {log} && bcftools index   {output} """
```

**Comment by dlaehnemann** [comment]
I think, contrary to the `[E::` at the start of the message, this is not actually an error, but only a warning, and `bcftools filter` works without the index file. Or are you seeing this rule fail because of this error?

And should this really be a hard failure, we would need to fix this in the [`bcftools filter` wrapper](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/bcftools/filter.html), requiring the bcf index file as an input there. Here, in the workflow, this would then mean adjusting the input to `rule filter_offtarget_variants` to also include the index file, which should then automatically be created by the `rule bcftools_index` in `workflow/rules/utils.smk`:

https://github.com/snakemake-workflows/dna-seq-varlociraptor/blob/9d271ef3bf235f2dd63616d08d3b4e3f22cbe019/workflow/rules/utils.smk#L1-L11

**Comment by dlaehnemann** [comment]
Do you have any follow-up info here, or can we close this? Namely, is this really just an irritating warning that sounds like an error, but does not actually stop/fail the workflow.

**Comment by user-tq** [comment]
> Do you have any follow-up info here, or can we close this? Namely, is this really just an irritating warning that sounds like an error, but does not actually stop/fail the workflow.

![image](https://user-images.githubusercontent.com/72878144/224974169-e48f344f-b6bb-43bb-90ff-cc46be4fa96d.png)
I conducted some simple tests. I found that if there is no index, when the bcftools filter uses the ```--regions-file``` option, this error will be triggered  and the program will be interrupted
![image](https://user-images.githubusercontent.com/72878144/224977483-71437d86-ac0d-4063-ac33-2aa98b33dae2.png)

**Comment by dlaehnemann** [comment]
One little meta-suggestion: You can paste in verbatim code and error messages as blocks here on GitHub, using a line with three backticks (```) to start a block and a line with three backticks (```) to close the block. That way the code / error message is nicely rendered (the screenshots have very small text) and can also be searched. For more detailed docs, see here:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by user-tq** [comment]
> One little meta-suggestion: You can paste in verbatim code and error messages as blocks here on GitHub, using a line with three backticks (`) to start a block and a line with three backticks (`) to close the block. That way the code / error message is nicely rendered (the screenshots have very small text) and can also be searched. For more detailed docs, see here: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

Thanks for your suggestion！I learned a lot from talking with you！

**Comment by dlaehnemann** [comment]
Thanks. As the thorough fix over with the snakemake wrapper is now merged, I'll close this issue here, as well.

But please do report any other issues that come up for you. These workflows always have so many corner cases that are not necessarily covered by the CI, so this kind of feedback is really important for everybody using these workflows!
